development:
    dialect: mysql
    datasource: ${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_ADDRESS}:${MYSQL_PORT})/$MYSQL_DATABASE?charset=utf8&parseTime=True&loc=Local
    dir: ./migrations
    table: migrations

seed:
    dialect: mysql
    datasource: ${MYSQL_USERNAME}:${MYSQL_PASSWORD}@tcp(${MYSQL_ADDRESS}:${MYSQL_PORT})/$MYSQL_DATABASE?charset=utf8&parseTime=True&loc=Local
    dir: ./seeds
    table: seeds

drone_migrate:
    dialect: mysql
    datasource: 127.0.0.1:3306/$MYSQL_DATABASE
    dir: ./migrations
    table: migrations

drone_seed:
    dialect: mysql
    datasource: 127.0.0.1:3306/$MYSQL_DATABASE
    dir: ./seeds
    table: seeds